### ISSUE TITLE
Provider CMAKE_EXPORT_COMPILE_COMMANDS is removed from project

### ISSUE THREAD

**Issue by asterkrans** [15knots/cmake4eclipse#102] opened 2019-01-22 08:31 UTC
**This is a...**  
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
When a project is re-imported to the workspace or imported to a new workspace, the Language Settings Providers settings are reseted to the defaults. That is CMAKE_EXPORT_COMPILE_COMMANDS is no longer used, and CDT Managed Build Settings are enabled again.

### What is the expected behavior?
Expect project to be intact after re-import / import to new workspace.

### What behavior are you observing?
The configuration provider settings are reseted to the defaults. That is CMAKE_EXPORT_COMPILE_COMMANDS is no longer used, and CDT Managed Build Settings are enabled.

### Provide the steps to reproduce the issue, if applicable:
1. Create a project using the cmake4eclipse getting started guide. NOTE: You need to update the Quick start section in README.md after the name change in Eclipse help)
1. Enable CMAKE_EXPORT_COMPILE_COMMANDS Provider under Project properties -> C/C++ General -> Preprocessor includes... . Disable the other providers.
1. Close the project.
1. Delete the project. (Do not delete resources)
1. Import the project again. (Import -> General -> Existing projects into workspace)
1. Check preferences for the project. The Language Settings Providers have now been reseted to defaults. CMAKE_EXPORT_COMPILE_COMMANDS Provider not enabled any more.

## Useful Information
- cmake4eclipse version: 1.13.0 (Seen in older versions too. Tested 1.11.0 and 1.12.2)
- Which OS do you use: Ubuntu 16.04
- Cmake version: 3.8.2

**Comment by asterkrans** [comment] 2019-01-22 10:39
I don't know if this is related or not, but I also see that the providers are marked [Shared] (shared within workspace) even when _prefer-non-shared="true"_ is present in _language.settings.xml_.

**Comment by 15knots** [comment] 2019-01-22 20:53
I cannot reproduce this here with CDT 8.7. The CMAKE_EXPORT_COMPILE_COMMANDS Provider are not lost.
My settings.xml looks like this
```
<extension point="org.eclipse.cdt.core.LanguageSettingsProvider">
	<provider-reference id="de.marw.cmake.cdt.language.settings.providers.BuiltinsCompileCommandsJsonParser" ref="shared-provider"/>
	<provider-reference id="de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser" ref="shared-provider"/>
</extension>
```

But with CDT 9.5.3 it **is** reproducible. Looks like CDT sets the providers to its internal defaults, when importing a project. Possibly a regression in CDT.

**Comment by 15knots** [comment] 2019-03-07 20:28
Closing this as duplicate of
#104 language.settings.xml reverted upon project import

**Closed by 15knots** 2019-03-07 20:28 UTC
