### ISSUE TITLE
Unable to retrieve CMake4Eclipse from Eclipse IDE

### ISSUE THREAD

**Issue by LucasDDF** [15knots/cmake4eclipse#153] opened 2021-05-20 12:59 UTC
Hello, 

I'm facing an issue with your CMake4Eclipse pluggin. I systematically fail when I try to retrieve it from my Eclipse IDE (v. 2021-03 (4.19.0)).

See the enclosed picture with the error logs but it seems that I somehow fail to reach your endpoint. 

Any idea ? 

![Capture](https://user-images.githubusercontent.com/84512361/118982436-ba247700-b97b-11eb-8cad-f2c2917f9d30.JPG)

**Comment by danderson-presonus** [comment] 2021-05-20 18:17
I have the same problem, I think the root cause is that the binary hosting service is down and has not been replaced by anything.  I just tried to build from source on Ubuntu 20.04 and that fails also with the attached build log.

[buildlog.txt](https://github.com/15knots/cmake4eclipse/files/6517987/buildlog.txt)

**Comment by mkbel** [comment] 2021-05-21 09:36
I think it is related to #149 Bintray end of service.

**Comment by 15knots** [comment] 2021-05-22 16:12
Duplicate of #149

**Comment by mindThomas** [comment] 2021-05-23 03:53
@danderson-presonus I am getting the same build problem. Did you manage to resolve local building while we are waiting for a new binary mirror?

**Comment by danderson-presonus** [comment] 2021-05-25 16:11
Nope, I don't really know Java or the associated tooling so I haven't spent any time trying to sort it out.  I'm hoping somebody with a bit more domain knowledge takes it on.

**Comment by 15knots** [comment] 2021-05-30 17:21
serving from cloudsmith.io now

**Closed by 15knots** 2021-05-30 17:21 UTC
Labels: duplicate
