### ISSUE TITLE
Includes are not properly indexed on Eclipse restart

### ISSUE THREAD

**Issue by Algomorph** [15knots/cmake4eclipse#109] opened 2019-02-07 14:29 UTC
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Includes are not properly indexed on Eclipse restart.
**Not sure whether this is a CDT bug or a cmake4eclipse bug.**
Please see https://bugs.eclipse.org/bugs/show_bug.cgi?id=543882

## Brief Summary
Includes are not reparsed if Eclipse is re-opened (or in other conditions, i.e. project closed & re-opened within eclipse). 

**Workaround** So far I had to re-run CMake by "force CMake to run with each build" and rebuilding, and then re-index the project in order for headers to be properly rediscovered.

## Useful Information
- cmake4eclipse version:   1.13.0.201901031836
- Which OS do you use: Linux Ubuntu 18.04 (up-to-date)
- Cmake version: 3.12.3
#### What is in Eclipse's Error Log?
There are some entries with "de.marw" that allude to something about the Boost library, but I don't think they are related, since the projects I have use other libraries than Boost (for instance, Eigen), and their headers are not found either. Attaching sanitized log.

Sanitized stack traces:
!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 16:56:32.971
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:09:24.535
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:11:48.075
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:27:32.099
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:27:59.047
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:28:21.745
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:31:27.208
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:31:59.256
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-06 17:33:28.262
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-07 07:51:18.084
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

!ENTRY de.marw.cdt.cmake.core 1 0 2019-02-07 08:33:52.518
!MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. Did the build run in a container?

**Comment by Algomorph** [comment] 2019-02-07 15:25
Example: this file is included in the cmake for the target. Eigen is not recognized, despite being listed under CMAKE_EXPORT_COMPILE_COMMANDS Parser in the Setting Entries.

![image](https://user-images.githubusercontent.com/1050606/52421542-3dc73c00-2ac2-11e9-8dfa-75bab140ef4d.png)

P.S. "Contradictions do not exist. Whenever you think you are facing a contradiction, check your premises." - Ayn Rand

**Comment by 15knots** [comment] 2019-02-07 20:27
`Includes are not reparsed if Eclipse is re-opened (or in other conditions, i.e. project closed & re-opened within eclipse).`
What exactly does **Includes** stand for in this case?
Is it the Includes folder in the Project Explorer view? If so, my comment on [UI update](https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cmake/src/main/java/de/marw/cmake/cdt/language/settings/providers/CompileCommandsJsonParser.java#L253-L256) might explain this issue.
In the image you posted, I can see that the settings provider properly recognized the include paths you specified in your CMakeLists.txt (such as the eigen3 directory).

> !MESSAGE Could not map /usr/share/cmake-3.12/Modules/FindBoost.cmake to a workspace resource. 

This comes from the cmake error parser. It has nothing to do with indexing. The parser detected a cmake error message that stems from /usr/.../FindBoost.cmake file. This file is not a workspace resource, so the error parser complained since it could not create an error marker that will open FindBoost.cmake if you double click the marker. The _CDT Global Build Console_ will show you the exact error message, anyway.

**Comment by Algomorph** [comment] 2019-02-07 22:13
@15knots It's not just the Project Explorer view I'm talking about. Everything "Eigen" is painted over with red squiggly lines, code-completion doesn't work, and any other features related to indexing don't work -- the header isn't there anymore once you close eclipse and reopen it. It requires me to switch build configurations & rebuild with CMake re-run for the include to be parsed again properly.

**Comment by Algomorph** [comment] 2019-03-04 14:18
@15knots were you able to reproduce? How do we establish whether this is a CDT issue or a cmake4eclipse issue? -Thanks

**Comment by 15knots** [comment] 2019-03-04 22:15
> @15knots were you able to reproduce? 

Well, I did not yet try your example to reproduce. I tried my `C-inclpaths` sample project which does essentially the same: Causing a `-I/non/standard/incl/path` option in the generated `compile_commands.json` file. But could not reproduce with CDT 9.5.5.
> How do we establish whether this is a CDT issue or a cmake4eclipse issue?

I think it's a CDT issue.
Reading the CDT javadocs and [WTFAQ](https://wiki.eclipse.org/CDT/Developer/FAQ), I could not find any information whether a `LanguageSettingsProvider` is supposed to trigger indexing **at all** nor **when.** None of the `LanguageSettingsProvider`s existing in CDT care about the indexer (Although cmake4eclipse calls IIndexManager.update()).

**Comment by Algomorph** [comment] 2019-03-05 14:56
@15knots in this case, 
(1) would it be too much to ask to vote and weigh in on the CDT [Bug 543882](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543882)?

Any potential solutions / thoughts and an upvote would be much appreciated.

(2) Should this issue be closed as invalid or kept open until Bug 543882 is resolved?

Thanks again -- your plugin + CDT literally saved me when I discovered that CLion chokes on projects involving the Eigen library.

**Comment by 15knots** [comment] 2019-03-05 21:07
> (2) Should this issue be closed as invalid or kept open until Bug 543882 is resolved?

Leave it open, as it is referenced on the CDT bug tracker.

**Comment by havogt** [comment] 2019-04-20 21:22
Possibly this is a problem related to upgrading a workspace to a new cdt version:
@Algomorph Can you go to project properties -> Project Natures and check if `Scanner Configuration Nature` is there. If it is there, remove it, `close and apply`. Then open properties again and add it (search for`Scanner Configuration Nature` and choose the second). Let me know if this fixes your issue.
@15knots I was able to reproduce the problem with `C-inclpaths` and a recent CDT (actually the master).

**Comment by Algomorph** [comment] 2019-04-22 17:17
@havogt I followed the steps and re-launched Eclipse to test, it seems to be fixed now (though I had to select the first `Scanner Configuration Nature`, not the second one, because the second one generated an error -- some problem related to Makefile projects).
Thank you!
I hope the problem doesn't come back...

**Comment by Algomorph** [comment] 2019-04-23 14:15
@havogt , so no, unfortunately it came back.
I figured another critical detail about replicating this. I have to exit eclipse when Release configuration is active. If I exit in "Debug", everything seems normal when I start again. When I start in Release again, index is gone... And I have to rebuild in Debug, that's what's interesting. That's what I've been doing for ~6 months now, rebuilding in Debug on every single project every time I restart the IDE, to continue developing in Release (cause the tests run faster with optimization + other reasons). 

I've re-added the "first" `Scanner Configuration Nature`, since the second one requires the `CDT Make Natrue` as a prerequisite. Is this correct? Or should I try adding the second one _and_ the `CDT Make Nature`?

**Comment by 15knots** [comment] 2019-06-08 12:41
> When I start in Release again, index is gone... And I have to rebuild in Debug, that's what's interesting.

Could this be ralated to the worksbench indexer settings in _Build configuration for the indexer_?

**Comment by Algomorph** [comment] 2019-06-11 17:02
@15knots I'm not sure, I'll try to check when I have time (I'm preparing right now for something very important). If it is, it must be something that  3 of my ubuntu machines share after installing eclipse + cdt + cmake4eclipse. I'm baffled that nobody but me has "+1" this yet since the other person's report on the CDT bug tracker: all you need to replicate this should be Ubuntu + CDT + cmake4eclipse, do a Release build on a library project, exit eclipse and relaunch it.

**Comment by 15knots** [comment] 2020-09-15 18:57
Closing this after waiting more than a year for feed-back.

**Closed by 15knots** 2020-09-15 18:57 UTC
Labels: feedback awaited

**Comment by Algomorph** [comment] 2020-09-17 12:30
@15knots yes, my apologies about not getting back to you. I must have got really involved in whatever I was doing and didn't remember because I switched back to CLion... My bad. If I ever run into this again, I'll post details here and we'll reopen.
