### ISSUE TITLE
Include directories are not updated automatically (CMake Compilation DB)

### ISSUE THREAD

**Issue by inxksp** [15knots/cmake4eclipse#193] opened 2023-11-09 09:59 UTC
In the project tree, icludes directories are updated only after closing and opening the project, update (F5) has no effect

**Comment by 15knots** [comment] 2023-11-10 20:20
fixed in ad670ec26eafa260eeb53887656823de7d9748a1

**Closed by 15knots** 2023-11-10 20:20 UTC

**Comment by ksrp1984** [comment] 2024-08-20 17:07
> fixed in [ad670ec](https://github.com/15knots/cmake4eclipse/commit/ad670ec26eafa260eeb53887656823de7d9748a1)

The problem is back: latest version of the plugin
Tested on Windows and Linux

**Comment by 15knots** [comment] 2024-08-20 19:19
Did you update CDT too or not? Just to make shure CDT isn't the culprit.

**Comment by ksrp1984** [comment] 2024-08-21 03:34
> Did you update CDT too or not? Just to make shure CDT isn't the culprit.

![image](https://github.com/user-attachments/assets/98450d24-f056-432b-b491-fa27288db28f)

**Comment by inxksp** [comment] 2024-08-21 05:28
> isn't the culprit.
It seems the problem only appears during the first compilation.
Check:
1. Delete directory _build
2. Close project
3. Close Eclipse
4. Open Eclipse and project
5. Run compilation
