### ISSUE TITLE
Includes outside the project are not indexed

### ISSUE THREAD

**Issue by kutschkem** [15knots/cmake4eclipse#93] opened 2018-11-09 16:52 UTC
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description

The UI shows false positive missing imports and compiler errors for headers outside of the project (for example, when using find_package and including that packages INCLUDE_DIRS). The build works fine.

I also tried enabling the Providers as mentioned in #45, but none of them helped.

## (If Bug Report) Brief Summary

This was observed with version 1.12.2 on Windows 7, with the NMake Makefile generator.

### What is the expected behavior?

A header on the include path of a target should be indexed for those source files. If it is not possible to seperate the indexes per target, then the second best thing would be to index the headers for the whole project, and risk missing some errors in the UI (they will be caught by building).

### What behavior are you observing?

For headers outside of the project (third-party libraries), the include are not resolved by the indexer, and show errors.

### Provide the steps to reproduce the issue, if applicable:

1. 
1. 
## Useful Information
cmake4eclipse verssion: 1.12.2
Which OS do you use: Windows 7
Cmake version: 3.10.0

**Comment by 15knots** [comment] 2018-11-09 20:48
> For headers outside of the project (third-party libraries), the include are not resolved by the indexer, and show errors.
Where in the UI do these errors show up and what are the error messages?

Indexing of headers outside the project tree normally works fine, for example for system headers and include paths added with cmake`s `include_directories` command.
Could you have a look into the compile_commnds.json file? The include dirs should appear in the value of the "command" entries there. I'm testing with cmake 3.5.2 on linux, maybe the format of `compile_commnds.json` has changed or cmake does not write the dirs for the nmake generator.

**Comment by kutschkem** [comment] 2018-11-12 07:33
Here an example of one of the offending files:

```
{
  "directory": "C:/Users/<user name>/runtime-xcit-rcp.product/test_yaaf/build/Default/algos/ecal",
  "command": "C:\\LegacyApp\\VisualStudio2015\\VC\\bin\\cl.exe @<<
  /TP -DECAL_LAYER_FASTRTPS -D_SCL_SECURE_NO_WARNINGS -IC:\\LegacyApp\\VisualStudio2015\\VC\\INCLUDE -IC:\\LegacyApp\\VisualStudio2015\\VC\\ATLMFC\\INCLUDE -IC:\\PROGRA~2\\WI3CF2~1\\10\\include\\100177~1.0\\ucrt -IC:\\PROGRA~2\\WI3CF2~1\\NETFXSDK\\46D346~1.1\\include\\um -IC:\\PROGRA~2\\WI3CF2~1\\10\\include\\100177~1.0\\shared -IC:\\PROGRA~2\\WI3CF2~1\\10\\include\\100177~1.0\\um -IC:\\PROGRA~2\\WI3CF2~1\\10\\include\\100177~1.0\\winrt -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\_common\\implementation\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\_common\\ara\\include -ID:\\git\\XCitDevelopmentTooling\\yaaf\\_common\\cmake\\..\\simpleini -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\..\\..\\..\\algos\\visualization\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\..\\..\\..\\algos\\implementation\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\algos\\implementation\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\algos\\visualization\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\algos\\ecal\\include -IC:\\PROGRA~1\\eCAL\\cmake\\..\\lang\\C__~1\\PROTOB~1\\include -IC:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\algos\\implementation\\protobuf -ID:\\git\\XCitDevelopmentTooling\\yaaf\\_common\\cmake\\..\\spdlog\\include -IC:\\PROGRA~1\\eCAL\\lang\\C__~1\\ecal\\V140_W~1\\include  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /W4 /W4 -D_SCL_SECURE_NO_WARNINGS /MD /O2 /Ob2 /DNDEBUG   /FoCMakeFiles\\myAlgoName_ecal.dir\\src\\myAlgoNameEcalMain.cpp.obj /FdCMakeFiles\\myAlgoName_ecal.dir\\ /FS -c C:\\Users\\<user name>\\runtime-xcit-rcp.product\\test_yaaf\\projects\\build\\autogen\\algos\\ecal\\src\\myAlgoNameEcalMain.cpp
<<",
  "file": "C:/Users/<user name>/runtime-xcit-rcp.product/test_yaaf/projects/build/autogen/algos/ecal/src/myAlgoNameEcalMain.cpp"
}
```

What I see as potential issues for an indexer: Windows shortened paths, and paths with ".." in them. Do note that both `-ID:\\git\\XCitDevelopmentTooling\\yaaf\\_common\\cmake\\..\\spdlog\\include` and `-IC:\\PROGRA~1\\eCAL\\lang\\C__~1\\ecal\\V140_W~1\\include` are not indexed.

**Comment by 15knots** [comment] 2018-11-12 21:01
>   "command": "C:\\LegacyApp\\VisualStudio2015\\VC\\bin\\cl.exe @<<

What is that `@<<` argument for? Could be fooling the parser. Is ther a file named `<<` in the build directory?

> What I see as potential issues for an indexer: Windows shortened paths, and paths with ".." in them. 

These are valid file system paths, so the indexer should be able to handle it. There was a related issue with short paths (#31), but that was fixed for the compiler command only. Performing short-path resolution for each include argument would have some performance penalty.
BTW: Do the non-indexed include dirs actually exist?

**Comment by kutschkem** [comment] 2018-11-13 08:54
I think `@<<` is actually the `@` [option of cl.exe](https://msdn.microsoft.com/de-de/library/610ecb4h.aspx) which lets the user specify a file which contains the compiler flags. and then `<<` is used to specify the file inline (this ends with the second `<<` that you can see.
No there is no file of that name, yes the directories exist. Maybe the indexer is confused by the `\\`?

**Comment by 15knots** [comment] 2018-11-13 21:03
The parser already has a  handler for the `@commandfile` syntax. So if the file name `<<` does not exist, you should find an exception logged in eclipses error log.

Is the `@<<...<<` just your guess or is it documented somewhere?

BTW: The `@commandfile`  syntax was invented to overcome limitations in the length of a command-line. But what sense does it make then, if the content of the commandfile is specified on the command-line itself?

**Comment by kutschkem** [comment] 2018-11-14 07:37
Yes I found documentation here: https://en.wikipedia.org/wiki/Here_document#Microsoft_NMAKE

**Comment by kutschkem** [comment] 2018-11-14 12:48
And here is the stacktrace you were looking for:

```
java.nio.file.InvalidPathException: Illegal char <<> at index 88: C:\Users\uidj1662\runtime-xcit-rcp.product\test_yaaf\build\Default\algos\implementation\<<
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at de.marw.cmake.cdt.language.settings.providers.ResponseFileArgumentParsers$At.process(ResponseFileArgumentParsers.java:73)
	at de.marw.cmake.cdt.language.settings.providers.ToolCommandlineParser$ParserHandler.parseArguments(ToolCommandlineParser.java:157)
	at de.marw.cmake.cdt.language.settings.providers.ToolCommandlineParser$ParserHandler.access$1(ToolCommandlineParser.java:140)
	at de.marw.cmake.cdt.language.settings.providers.ToolCommandlineParser.processArgs(ToolCommandlineParser.java:71)
	at de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser.processCommandLine(CompileCommandsJsonParser.java:465)
	at de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser.processJsonEntry(CompileCommandsJsonParser.java:314)
	at de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser.tryParseJson(CompileCommandsJsonParser.java:236)
	at de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser.determineBuiltinDetectors(CompileCommandsJsonParser.java:356)
	at de.marw.cmake.cdt.language.settings.providers.BuiltinsCompileCommandsJsonParser.detectBuiltins(BuiltinsCompileCommandsJsonParser.java:83)
	at de.marw.cmake.cdt.language.settings.providers.BuiltinsCompileCommandsJsonParser.shutdown(BuiltinsCompileCommandsJsonParser.java:156)
	at org.eclipse.cdt.internal.core.ConsoleOutputSniffer.closeConsoleOutputStream(ConsoleOutputSniffer.java:160)
	at org.eclipse.cdt.internal.core.ConsoleOutputSniffer$ConsoleOutputStream.close(ConsoleOutputSniffer.java:68)
	at org.eclipse.cdt.internal.core.ProcessClosure$ReaderThread.close(ProcessClosure.java:98)
	at org.eclipse.cdt.internal.core.ProcessClosure.isAlive(ProcessClosure.java:191)
	at org.eclipse.cdt.core.CommandLauncher.waitAndRead(CommandLauncher.java:273)
	at org.eclipse.cdt.core.CommandLauncherManager$CommandLauncherWrapper.waitAndRead(CommandLauncherManager.java:159)
	at org.eclipse.cdt.internal.core.BuildRunnerHelper.build(BuildRunnerHelper.java:275)
	at org.eclipse.cdt.managedbuilder.core.ExternalBuildRunner.invokeExternalBuild(ExternalBuildRunner.java:130)
	at org.eclipse.cdt.managedbuilder.core.ExternalBuildRunner.invokeBuild(ExternalBuildRunner.java:70)
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.invokeBuild(CmakeBuildRunner.java:124)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:753)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:510)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:459)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by kutschkem** [comment] 2018-11-14 13:05
Regarding the BTW: What do I know, that falls out of the generator. I can only assume that this allows splitting a long commandline over multiple lines maybe? At least that would be in line what you say this `@commandfile` is for in the first place.

**Comment by 15knots** [comment] 2018-11-14 20:54
Gnaah `@<<...<<`. And cmake really generates that stuff.
That*s a candidate for submission to  [The Daily WTF: Curious Perversions in Information Technology](http://thedailywtf.com/) .

Anyway, the exception should not harm; it is just logged and then ignored.

**Comment by 15knots** [comment] 2018-11-16 20:13
> Anyway, the exception should not harm; it is just logged and then ignored.

No it is not! 
Duplicate of/ caused by #94.

**Closed by 15knots** 2018-11-16 20:13 UTC
