### ISSUE TITLE
language.settings.xml reverted upon project import

### ISSUE THREAD

**Issue by daniel-dnil** [15knots/cmake4eclipse#104] opened 2019-02-04 19:47 UTC
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

Setup
=====
eclipse.buildId=4.10.0.I20181206-0815
CDT: 9.6.0.201812111211
cmake4eclipse: 1.13.0.201901031836
OS: Linux Mint 19
cmake version 3.10.2

Common Prepare
==============
git clone https://github.com/daniel-dnil/cm4e-tc.git && cd cm4e-tc

TC2: language.settings.xml reverted upon project import
==================================================

Note: This is a duplicate of https://github.com/15knots/cmake4eclipse/issues/102 but I'm keeping it
here anyway since it has references to a testcase and steps to reproduce.

1) git checkout 6c5a8c8

2) Continue working in TC1 WS above, a file proj-cn/.settings/org.eclipse.cdt.managedbuilder.core.prefs is created with
   contents that is not clear how this is relevent to this plugin. Keep this file in the repository for this TC.
```
$ cat proj-cn/.settings/org.eclipse.cdt.managedbuilder.core.prefs
eclipse.preferences.version=1
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/CPATH/delimiter=\:
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/CPATH/operation=remove
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/CPLUS_INCLUDE_PATH/delimiter=\:
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/CPLUS_INCLUDE_PATH/operation=remove
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/C_INCLUDE_PATH/delimiter=\:
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/C_INCLUDE_PATH/operation=remove
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/append=true
environment/buildEnvironmentInclude/cdt.managedbuild.config.gnu.exe.debug.960404064/appendContributed=true
```
3) Setup a new empty WS and import C-1src from folder proj-cn into this WS. Now
   project builds but the provider information is completely reverted back to CDT defaults ???
```
diff --git a/proj-cn/.settings/language.settings.xml b/proj-cn/.settings/language.settings.xml
index 7de4ced..89d2ff7 100644
--- a/proj-cn/.settings/language.settings.xml
+++ b/proj-cn/.settings/language.settings.xml
@@ -2,8 +2,13 @@
 <project>
        <configuration id="cdt.managedbuild.config.gnu.exe.debug.960404064" name="Debug">
                <extension point="org.eclipse.cdt.core.LanguageSettingsProvider">
-                       <provider-reference id="de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser" ref="shared-provider"/>
-                       <provider-reference id="de.marw.cmake.cdt.language.settings.providers.BuiltinsCompileCommandsJsonParser" ref="shared-provider"/>
+                       <provider copy-of="extension" id="org.eclipse.cdt.ui.UserLanguageSettingsProvider"/>
+                       <provider-reference id="org.eclipse.cdt.core.ReferencedProjectsLanguageSettingsProvider" ref="shared-provider"/>
+                       <provider-reference id="org.eclipse.cdt.managedbuilder.core.MBSLanguageSettingsProvider" ref="shared-provider"/>
+                       <provider class="org.eclipse.cdt.managedbuilder.language.settings.providers.GCCBuiltinSpecsDetector" console="false" env-hash="1036888353926601946" id="org.eclipse.cdt.managedbuilder.core.GCCBuiltinSpecsDetector" keep-relative-paths="false" name="CDT GCC Built-in Compiler Settings" parameter="${COMMAND} ${FLAGS} -E -P -v -dD &quot;${INPUTS}&quot;" prefer-non-shared="true">
+                               <language-scope id="org.eclipse.cdt.core.gcc"/>
+                               <language-scope id="org.eclipse.cdt.core.g++"/>
+                       </provider>
                </extension>
        </configuration>
 </project>
```
   I'm not completely sure, but this revert back to CDT defaults only seems to happen upon project import and it might be
   related to the proj-cn/.settings/org.eclipse.cdt.managedbuilder.core.prefs file being present in the project directory.
   It might also be some race condition since I think I've been able to have the language.settings.xml reset also 
   when the org.eclipse.cdt.managedbuilder.core.prefs is not present.

4) Close the Eclipse project, reset the language.settings.xml (git reset --hard HEAD) and re-open the project to
   get back to normal operation again. This is a very confusing problem when sharing the Eclipse projects in teams.

**Comment by 15knots** [comment] 2019-02-05 20:47
> In #102 it is suggested this is due to a CDT issue, but I'm not so sure about that. The CDT issue pointed to is over a year old...

Look at [open CDT bugs by date](https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&order=changeddate%2Cproduct%2Cpriority%2Cbug_severity&product=CDT&query_format=advanced) and you will find bugs more than 14 years old.

Well each of the providers in your language.settings.xml. has an ID starting with 'org.eclipse.cdt'.
Providers are **not** removed with CDT 8.7, so I am quite sure that this is a CDT bug. 

To reproduce, I deleted the project from the workspace and re-imported it .After  re-import, the language.settings.xml has differences to the HEAD revision in SCM.

**Comment by daniel-dnil** [comment] 2019-02-05 21:09
Two of the providers I used in my example are from plugins not part of CDT, check lines 13 and 32 in  the example above again:

```
id="ilg.gnuarmeclipse.managedbuild.cross.GCCBuiltinSpecsDetector"
id="ilg.gnumcueclipse.managedbuild.cross.riscv.GCCBuiltinSpecsDetector"
```

**Comment by 15knots** [comment] 2019-02-09 18:08
Checked here with CDT 8.5.3:

1. Create a new C Project
2. Just move GCC Built-in Compiler Settings provider to the top in the Providers tab
3. Apply and Close
4. Delete project from workspace
5. Import project into workspace

All provider settings are now set to the default. GCC Built-in Compiler Settings provider is now the last provider in the list.

This has to be fixed in CDT itself.

**Comment by daniel-dnil** [comment] 2019-02-13 20:00
I took a closer looks at what is happening inside CDT when this issue occurs, in function loadLanguageSettings(ICProjectDescription prjDescription) in LanguageSettingsProvidersSerializer.java there is a check if the file language.settings.xml exists in the workspace using the following functions;

IProject project = prjDescription.getProject();
IFile storeInPrjArea = getStoreInProjectArea(project);
boolean isStoreInProjectAreaExist = storeInPrjArea.exists();

This functions is executed a few times during import, and the first time it is executed storeInPrjArea.exists() returns false, this has the effect that language.settings.xml is created in the workspace using defaults.

I don't know why this is happening now and why I can't reproduce this using other CDT plugins that also store settings in language.settings.xml.

Call stack looks like this on the first check in loadLanguageSettings() when the file is reset;

isStoreInProjectAreaExist returns false

Thread [ModalContext] (Suspended (breakpoint at line 1208 in LanguageSettingsProvidersSerializer))	
	owns: RefreshScopeManager  (id=511)	
	owns: WizardProjectsImportPage$16  (id=512)	
	LanguageSettingsProvidersSerializer.loadLanguageSettings(ICProjectDescription) line: 1208	
	XmlProjectDescriptionStorage.loadProjectDescription(IProject) line: 511	
	XmlProjectDescriptionStorage.getProjectDescription(int, IProgressMonitor) line: 240	
	CProjectDescriptionManager.getProjectDescriptionInternal(IProject, int) line: 426	
	CProjectDescriptionManager.getProjectDescription(IProject, int) line: 408	
	CProjectDescriptionManager.getProjectDescription(IProject, boolean, boolean) line: 402	
	CProjectDescriptionManager.getProjectDescription(IProject, boolean) line: 395	
	RefreshScopeManager.loadSettings(IWorkspaceRoot, IProject) line: 474	
	RefreshScopeManager$1$1.visit(IResourceDelta) line: 154	
	ResourceDelta.accept(IResourceDeltaVisitor, int) line: 64	
	ResourceDelta.accept(IResourceDeltaVisitor, int) line: 74	
	ResourceDelta.accept(IResourceDeltaVisitor) line: 48	
	RefreshScopeManager$1.resourceChanged(IResourceChangeEvent) line: 142	
	NotificationManager$1.run() line: 297	
	SafeRunner.run(ISafeRunnable) line: 42	
	NotificationManager.notify(ResourceChangeListenerList$ListenerEntry[], ResourceChangeEvent, boolean) line: 287	
	NotificationManager.broadcastChanges(ElementTree, ResourceChangeEvent, boolean) line: 150	
	Workspace.broadcastPostChange() line: 376	
	Workspace.endOperation(ISchedulingRule, boolean) line: 1499	
	Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor) line: 2302	
	Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2316	
	WizardProjectsImportPage$16(WorkspaceModifyOperation).run(IProgressMonitor) line: 128	
	ModalContext$ModalContextThread.run() line: 119

**Comment by 15knots** [comment] 2019-03-07 20:26
CDT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=530708.

Cannot reproduce with
CDT 9.5.5.201811180605
CDT Container launch support 9.5.5.201811180605

**Closed** 2022-03-30 19:17 UTC
Labels: not a bug here
