### ISSUE TITLE
build fails if build directory is a symlink

### ISSUE THREAD

**Issue by nolange** [15knots/cmake4eclipse#30] opened 2017-04-12 12:32 UTC
Hello,

if you create a minimal project, and make the "build" directory a symlink (say to a folder on /tmp), then cmake will mix relative and absolutely resolved paths. Both ninja and make will then fail to build the project.

This is already an issue with cmake, but using /tmp for builds is a common practice. Please resolve the build directory (like "readlink -f" would do) and cd to the absolute path before invoking cmake

**Comment by nolange** [comment] 2017-04-13 07:54
Here is a project showing the various variants to start a CMake build.
I am talking about the "link" case which could fixed like its done with "linkabs" (resolve path and cd to it).
[cmakebuild.tar.gz](https://github.com/15knots/cmake4eclipse/files/918799/cmakebuild.tar.gz)

**Comment by 15knots** [comment] 2017-04-26 18:26
Cannot reproduce on linux with cmake version 2.8.11.2.

**Comment by nolange** [comment] 2017-04-26 20:24
did you run `make/ninja -C link/Debug` after the build.sh script?
I can reproduce with cmake 2.8.12.2 and cmake 3.8.

**Comment by 15knots** [comment] 2017-05-08 19:19
> did you run make/ninja -C link/Debug

No.
I disabled 'Project|Build automatically' in Eclipse, `rf -rf`-ed the build directory and created a symlink of the same name which pointed to `/tmp` from a command-line shell. 
After that, I ran 'Project|Build' in Eclipse. No problems found; neither with `<project-root>/build/Debug` being a symlink nor with `<project-root>/build`.

**Comment by nolange** [comment] 2017-05-08 20:23
did you use some source files in the project?

**Comment by 15knots** [comment] 2017-05-09 18:53
Yes, I had sources. I guess the project I tested was [C-flat](https://github.com/15knots/cmake4eclipse/tree/master/testprojects/C-flat), one of my test-projects here.

**Comment by 15knots** [comment] 2018-05-31 20:02
Closing this, since feedback was requested and no feedback arrived in more than one year. Re-open, if necessary.

**Closed by 15knots** 2018-05-31 20:02 UTC
Labels: feedback awaited

**Comment by nolange** [comment] 2018-08-06 12:03
I dont know what feedback was requested. I will try again with a step-by-step explanation:

1.   unpack the attached archive
2.   create the directory for the symlink: `mkdir -p $(readlink -m build)`
3.   open with eclipse and (try-to) build.

[cmakebuild.tar.gz](https://github.com/15knots/cmake4eclipse/files/2262420/cmakebuild.tar.gz)

**Comment by nolange** [comment] 2018-08-06 12:06
btw. never re-opened an issue, a google search say I cant do that unless I was the one closing them

**Comment by 15knots** [comment] 2018-08-06 18:39
The plugin is **designed** to create the build directory itself. If someone manually creates the build directory as a symlink, he will be fooling the plugin.
For your use-case _using /tmp for builds_, you will want to configure your eclipse project's _Build output location_ as a link to a folder in the file system. Use the Create... button and the Advanced button in the New Folder dialog; e.g. `tmp/${ProjName}/${ConfigName}`, where `tmp` is a linked resource which points to /tmp.

**Comment by nolange** [comment] 2018-08-06 20:46
> The plugin is designed to create the build directory itself. If someone manually creates the build directory as a symlink, he will be fooling the plugin.
aslong as the `build` symlink points to a valid directory, it should be no issue? The plugin can create the directory fine by the way, aswell as running CMake.
the symlink however will mess up when calling ninja/make (probably CMakes fault in the first place, see [This issue](https://gitlab.kitware.com/cmake/cmake/issues/16228) )

> For your use-case using /tmp for builds, you will want to configure your eclipse project's Build output location as a link to a folder in the file system. Use the Create... button and the Advanced button in the New Folder dialog; e.g. tmp/${ProjName}/${ConfigName}, where tmp is a linked resource which points to /tmp.

Thats nice, did not knew about this feature.
