### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by caselitz** [15knots/cmake4eclipse#82] opened 2018-06-18 17:03 UTC
When trying to install cmake4eclipse on Ubuntu 18.04 with Eclipse Oxygen 3a (java-11-openjdk) I get the following error:

> 
> Unable to read repository at https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/content.xml.
> java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

Any ideas?

**Comment by 15knots** [comment] 2018-06-18 17:45
Am Montag, 18. Juni 2018, 19:03:00 CEST schrieb Tim Caselitz:
> When trying to install cmake4eclipse on Ubuntu 18.04 with Eclipse Oxygen 3a 
(java-11-openjdk) I get the following error:
> > Unable to read repository at
> > https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/com
> > p-update/content.xml. java.lang.RuntimeException: Unexpected error:
> > java.security.InvalidAlgorithmParameterException: the trustAnchors
> > parameter must be non-empty
> Any ideas?

That resource does not exist. Should give a: 404 Not Found.
The p2 downloader in Eclipse probes for several files: content.jar, 
content.xml, compositeContent.xml, ... (I do not know the exact order)

<https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/compositeContent.xml> *does* exist. I do not know, why p2 gives up when 
content.xml is not found, IMHO it should try the other files before giving up.
Looks like a Java 11 issue, try Java 10 or lower. openJDK 8 definitely works.

/Martin

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by caselitz** [comment] 2018-06-25 16:18
Do you see any change to further investigate this? I think openjdk-11 will be the most common choice for Ubuntu 18.04 (which is the newest LTS release) users - so I guess there will be quite a few people running into this problem.

For other plugins, it seems to work, e.g., https://github.com/wangzw/CppStyle - not sure what's the difference but I feel it is not a Java 11 issue in general but maybe related to this repo?

Best,
Tim

**Comment by 15knots** [comment] 2018-06-25 18:37
Am Montag, 25. Juni 2018, 18:18:35 CEST schrieb Tim Caselitz:
> Do you see any change to further investigate this? I think openjdk-11 will

Sorry, my opensuse is still at Java 8.
But you could try in Java
new URL(...).openConnction() and see what happens.

> be the most common choice for Ubuntu 18.04 (which is the newest LTS
> release) users - so I guess there will be quite a few people running into
> this problem.
> 
> For other plugins, it seems to work, e.g.,
> https://github.com/wangzw/CppStyle - not sure what's the difference but I

That has a site.xml file, but noc compositeContens.xml

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by noyanc** [comment] 2018-06-30 14:21
I have the same issue on Ubuntu 16.04 & openjdk-9 & Eclipse Neon

**Comment by klahaag** [comment] 2018-07-20 10:40
I am on Ubuntu 18.04 using eclipse photon:
I deinstalled openjdk-11-jre and installed opendjdk-8-jre.
I am also encountering the above problem. This does not seem to be related to the jre version.

**Comment by 15knots** [comment] 2018-07-21 18:46
Am Freitag, 20. Juli 2018, 12:40:24 CEST schrieb Klaus Haag:
> I am on Ubuntu 18.04 using eclipse photon:
> I deinstalled openjdk-11-jre and installed opendjdk-8-jre.

Thinking of update-alternatives, I would ask: Are you sure to run java-8 now?

This could be caused by the lack of JCE (Java Cryptography Extensions) in your 
JRE.
At least openjdk 8 on opensuse comes with JCE bundled. In contrast, oracle JRE 
comes without JCE (both on windows and linux), you will have to install it 
manually.
Regarding ubuntu, I don't know whether it comes with JCE.

My current guess is that openjdk 9 and newer no longer come with JCE. Try to 
download & install from the oracle site.

> I am also encountering the above problem. This does not seem to be related
> to the jre version.


-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by klahaag** [comment] 2018-07-23 15:07
when I check Eclipse IDE Installation Details -> Configuration, I get:
`eclipse.vm=/usr/bin/java`
and when executing /usr/bin/java -version:
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
JCE seems to be installed as well (output from first answer https://stackoverflow.com/questions/13238074/how-to-check-that-java-cryptography-extension-is-installed):
```
SUN 1.8
SunRsaSign 1.8
SunEC 1.8
SunJSSE 1.8
SunJCE 1.8
SunJGSS 1.8
SunSASL 1.8
XMLDSig 1.8
SunPCSC 1.8
```

**Comment by 15knots** [comment] 2018-07-23 18:22
Am Montag, 23. Juli 2018, 17:07:34 CEST schrieb Klaus Haag:
> when I check Eclipse IDE Installation Details -> Configuration, I get:
> `eclipse.vm=/usr/bin/java`
> and when executing /usr/bin/java -version:
> ```
> openjdk version "1.8.0_171"
> OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
> OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)


> ```
> JCE seems to be installed as well (output from first answer
> https://stackoverflow.com/questions/13238074/how-to-check-that-java-cryptog
> raphy-extension-is-installed): ```
> SUN 1.8
> SunRsaSign 1.8
> SunEC 1.8
> SunJSSE 1.8
> SunJCE 1.8
> SunJGSS 1.8
> SunSASL 1.8
> XMLDSig 1.8
> SunPCSC 1.8
> ```

If its not the JCE, it could be a problem with the installed certificates.
In the OP, there is the stack entry
```
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter 
must be non-empty
```
wich lead me to the following: <https://stackoverflow.com/a/29313285/6461411>
But that bug should have been fixed now.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by 15knots** [comment] 2018-08-03 12:33
I also found this https://devtalk.nvidia.com/default/topic/1037981/unable-to-install-cmake4eclipse-in-nsight-/.
Try to run Eclipse with `-vmargs -Djava.net.preferIPv4Stack=true`

**Comment by 15knots** [comment] 2019-12-08 16:21
closing this after more than one year waiting for feedback

**Closed by 15knots** 2019-12-08 16:21 UTC
Labels: feedback awaited
