### ISSUE TITLE
Cannot build previously working project after reinstalling Eclipse+cmake4eclipse-3.0.0

### ISSUE THREAD

**Issue by ceggers-arri** [15knots/cmake4eclipse#165] opened 2022-01-26 09:34 UTC
**Describe the bug**
A previously working project cannot be built after reinstalling Eclipse+cmake4eclipse-3.0.0:

- Error message (Message box, seems related to #164).
> Errors occurred during the build.
> Errors running builder 'CDT Builder' on project 'main-application'.
> Name is null
- No entries visible in project properties --> _C/C++ Build --> Cmake4eclipse --> CMake Cache entries_
  -  In the previously used version of  cmake4eclipse, setting were visible under _C/C++ Build --> Cmake4eclipse --> Symbols_
  -  _Host OS Overrides_ was not in use

**To Reproduce**
1. Install Eclipse-CDT package 2021.12
2. Start with a fresh workspace
3. Install cmake4eclipse (and restart)
4. Import an existing project which has previously been used with Eclipse-2020.03 / cmake4eclipse-2.1.1
5. Try to build (using the hammer dropdown menu in the toolbar)
6. Check cmake4eclipse settings in project properties

**Expected behavior**
- Project should build without Eclipse error message
- Settings configured as _CMake symbols_ in cmake4eclipse-2.1.1 should be visible as _CMake cache entries_ in cmake4eclipse-3.0.0.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45507747/151137661-4af574b3-9063-4546-ba86-812426f1ec76.png)
![grafik](https://user-images.githubusercontent.com/45507747/151137731-878a45df-8b13-49cd-b06c-37bdb74f15dd.png)

**Useful Information**
- cmake4eclipse version: 2.1.1 / 3.0.0
- Which OS do you use: openSUSE Leap 15.3
- Cmake version: 3.17.0

***What is in Eclipse's Error Log?***

Sanitized stack traces:
!SESSION 2022-01-26 10:33:09.734 -----------------------------------------------
eclipse.buildId=4.22.0.I20211124-1800
java.version=17.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product -data .

!ENTRY org.eclipse.core.resources 4 2 2022-01-26 10:33:19.504
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException: Name is null
        at java.base/java.lang.Enum.valueOf(Enum.java:271)
        at de.marw.cmake4eclipse.mbs.settings.CmakeGenerator.valueOf(CmakeGenerator.java:1)
        at de.marw.cmake4eclipse.mbs.internal.BuildToolKitUtil.getEffectiveCMakeGenerator(BuildToolKitUtil.java:37)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.buildCommandline(BuildscriptGenerator.java:502)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.invokeCMake(BuildscriptGenerator.java:361)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.generateBuildscripts(BuildscriptGenerator.java:292)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.regenerateMakefiles(BuildscriptGenerator.java:199)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performMakefileGeneration(CommonBuilder.java:1011)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performPrebuildGeneration(CommonBuilder.java:874)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:754)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:520)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:463)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:516)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:413)
        at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.resources 4 75 2022-01-26 10:33:19.560
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.cdt.managedbuilder.core 4 75 2022-01-26 10:33:19.560
!MESSAGE Errors running builder 'CDT Builder' on project 'main-application'.
!STACK 0
java.lang.NullPointerException: Name is null
        at java.base/java.lang.Enum.valueOf(Enum.java:271)
        at de.marw.cmake4eclipse.mbs.settings.CmakeGenerator.valueOf(CmakeGenerator.java:1)
        at de.marw.cmake4eclipse.mbs.internal.BuildToolKitUtil.getEffectiveCMakeGenerator(BuildToolKitUtil.java:37)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.buildCommandline(BuildscriptGenerator.java:502)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.invokeCMake(BuildscriptGenerator.java:361)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.generateBuildscripts(BuildscriptGenerator.java:292)
        at de.marw.cmake4eclipse.mbs.internal.BuildscriptGenerator.regenerateMakefiles(BuildscriptGenerator.java:199)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performMakefileGeneration(CommonBuilder.java:1011)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performPrebuildGeneration(CommonBuilder.java:874)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:754)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:520)
        at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:463)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:516)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:413)
        at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by 15knots** [comment] 2022-01-26 21:43
Duplicate of #164

**Closed by 15knots** 2022-01-26 21:43 UTC
Labels: duplicate
