### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser does not evaluate "response files"

### ISSUE THREAD

**Issue by moetka** [15knots/cmake4eclipse#58] opened 2017-11-13 14:59 UTC
The make-type generators collect all includes in a separate "includes_CXX.rsp" file by default at least on windows
[compile_commands.json.txt](https://github.com/15knots/cmake4eclipse/files/1467222/compile_commands.json.txt)
[includes_CXX.rsp.txt](https://github.com/15knots/cmake4eclipse/files/1467223/includes_CXX.rsp.txt)

Using set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0) as described in https://stackoverflow.com/questions/9056507/output-include-paths-and-cmake did not make any difference

It would be nice if the parser would dive through these included files as well.

**Comment by 15knots** [comment] 2017-11-14 19:43
Maybe you will have to put the line
`set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0)` at a differn location in your CMakeLists.txt (before/after project())?

Yes, parsing the response files would be nice, but questions arise...

1. which command-line argument(s) designate a response file. The parser will have to know that for each of the five compilers on three different platforms currently supported?
1. what is the format of these files?

I'm on a linux box, where the problem does not arise/is hard to reproduce. Someone owning a windows box will have to put a PR to implement.

**Comment by 15knots** [comment] 2017-12-09 14:24
duplicate of #47 Include response file

**Closed** 2017-12-11 16:22 UTC
Labels: enhancement
