### ISSUE TITLE
ResourceException: Resource '/xyz/build/Debug/CMakeCache.txt' does not exist

### ISSUE THREAD

**Issue by arette** [15knots/cmake4eclipse#3] opened 2015-06-04 17:59 UTC
Using Eclipse 4.4 (Luna) and latest Cmake.
I've selected the CMake Builder (portable) as the active toolchain (under project properties C/C++ Build -> Tool Chain Editor), but the Eclipse generates an error dialogue when I attempt to build the project (see below).  Could it be the trailing '}' in the project name?  Looks like a bug in the parsing of my build directory (which is ${workspace_loc:/AE3007C2}/).  Please advise.

"
Errors occurred during the build.
Errors running builder 'CDT Builder' on project 'AE3007C2'.
Resource '/AE3007C2}/CMakeCache.txt' does not exist.
Resource '/AE3007C2}/CMakeCache.txt' does not exist.
"

**Comment by 15knots** [comment] 2015-06-04 18:25
I don't think it is the trailing  '}' in the project name.
I could reproduce that.
Can you find similar in your log?
´´´
!MESSAGE Errors running builder 'CDT Builder' on project 'C-1src'.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/C-1src/build/Debug/CMakeCache.txt' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:341)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:215)
	at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:221)
	at org.eclipse.core.internal.resources.Resource.getSessionProperty(Resource.java:1275)
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.getCommandFromCMakeCache(CmakeBuildRunner.java:129)
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.invokeBuild(CmakeBuildRunner.java:89)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:753)
´´´
Looks like a bug which happens only random.

**Comment by arette** [comment] 2015-06-04 18:39
I’ve done more testing and I believe it a bug in how the plugin parses Eclipse variables in the Build directory field.  It is not random, in fact, is completely repeatable.  If I move my project  and specify full path to the build directory, everything works.   Cmake4ecplise needs to be more robust in parsing the build directory as specified in Eclipse and turning it into a valid path on the file system.   Any idea when a fix can be released?  Are there other ways of invoking cmake from within Eclipse in the meantime (native or other 3rd party plug-ins)?

Anthony Ette
Systems Engineer
Simulation and Modeling

Controls and Data Services Inc.
Part of the Rolls-Royce Group

tel: +1 (317) 230-6943
mob: +1 (317) 864-7975
email: Anthony.R.Ette@controlsdata.com<mailto:Anthony.R.Ette@controlsdata.com>
www.controlsdata.com<http://www.controlsdata.com/>

**Comment by 15knots** [comment] 2015-06-04 19:18
[please refrain from top posting]

Am Donnerstag, 4. Juni 2015, 11:39:50 schrieb arette:
> I’ve done more testing and I believe it a bug in how the plugin parses
> Eclipse variables in the Build directory field.  It is not random, in fact,

How did you manage to edit the Build directory field on the builder settings 
tab without disabling 'Generate Makefiles automatically'?
The purpose of the plugin *is to generate the makefiles* (or ninjafiles). It 
does not parse any Eclipse variables.

Please make sure 'Generate Makefiles automatically' is checked.
Currently, the plugin generates all build-scripts under build/<configuration 
name> (to allow users to add 'build/' to their .gitignore).
If you are not satisfied with the hard-coded build-directory, feel free to 
file an issue for that.


> is completely repeatable.  If I move my project  and specify full path to
> the build directory, everything works.   Cmake4ecplise needs to be more
> robust in parsing the build directory as specified in Eclipse and turning

If the 'Generate Makefiles automatically' is unchecked, some quirky CDT 
variable expansion kicks in. See the comment in 
<https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cdt.cmake.core/src/main/java/de/marw/cdt/cmake/core/internal/CmakeBuildRunner.java>
 line 121. You can find similar comments in the CDT sources, too.

The stack-trace posted earlier comes from one of the examples project, where 
no variable expansion is configured.

Martin

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-04 19:37
Ok making it further with that option selected. Sorry for my earlier confusion, but I think I was somehow using an outdated cmakebuilder plugin at the time. But now I'm getting a problem with 'del' not found in path.  Suggestions?

15:32:50 **** Clean-only build of configuration Debug for project AE3007C2 ****
del src/common/Txcallback.obj src/net/net_comm.obj AE3007C2 src/files/files_w.obj src/fault_reset/fault_reset.obj src/models/main.obj src/common/initial_sil_data.obj src/ec_interface/ec_interface_w.obj src/common/initial_ctrl_data.obj src/common/set_SDIs.obj src/net/net_w.obj src/menu/menu.obj src/monitor/monitor.obj src/sil_test/sil_test_w.obj src/stripper/stripper.obj src/engine_controller/fadec_interface.obj src/sil_test/sil_test.obj src/files/files.obj src/engine_controller/fadec_w.obj src/interface/input_output.obj src/common/initial_data.obj src/remove/remove.obj src/common/readAppConfig.obj src/sil_test/UDP_server_w.obj src/common/stripper_sub.obj src/net/net.obj src/alt_control/alt_control.obj src/sil_test/sil_test_comm.obj src/net/UDP_client_w.obj src/net/net_overwrite.obj src/models/main_w.obj src/interface/interface.obj src/ec_interface/ec_interface.obj 
Cannot run program "del": Launching failed

Error: Program "del" not found in PATH
PATH=[C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\..\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\..\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages;C:\Program Files\Microsoft HPC Pack 2008 SDK\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Imaging\;C:\Windows;C:\Windows\SysWOW64;C:\ORACLE\ora92\jre\1.4.2\bin\client;C:\ORACLE\ora92\jre\1.4.2\bin;C:\ORACLE\ora92\bin;C:\Windows\SUA\common\;C:\Windows\SUA\usr\lib\;C:\Program Files (x86)\tcVis\83\Products\Mockup\ClearanceDB;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\MATLAB\R2010bSP1\runtime\win32;C:\Program Files (x86)\MATLAB\R2010bSP1\bin;C:\Windows\SysWOW64\;C:\Windows\SysWOW64\Wbem;C:\Windows\SysWOW64\WindowsPowerShell\v1.0;C:\Program Files (x86)\AdminStudio\11.5\Common;C:\PROGRA~1\MKS\Toolkit\mksnt;C:\Program Files (x86)\Intel\Compiler\Fortran\10.1.021\ia32\Lib;C:\Program Files (x86)\Intel\Compiler\Fortran\10.1.021\EM64T\Lib;C:\Program Files (x86)\MATLAB\MATLAB Compiler Runtime\v81\runtime\win32;C:\Users\bzpl46\APPS\TCL\bin;C:\Users\bzpl46\python273;C:\Users\bzpl46\Python273;C:\Users\bzpl46\sim\lib\v65\win32;C:\Users\bzpl46\sim\sandbox\tools\bin;C:\Users\bzpl46\sim\tools\bin\HAMMER;C:\Users\bzpl46\sim\sandbox\custom\bin;C:\Users\bzpl46\sim\sandbox\custom\lib;C:\Users\bzpl46\sim\sandbox\custom\pyshm\bin;C:\Users\bzpl46\sim\sandbox\custom\pyshm\lib;D:\cygwin\bin;C:\Users\bzpl46\sim\sandbox\tools\bin\Qtools;C:\Users\bzpl46\sim\tools\bin]


15:32:50 Build Finished (took 453ms)

**Comment by arette** [comment] 2015-06-04 19:41
And I think the default of putting build_scripts under build/<configuration name> is a poor choice: you're assuming the name of my Eclipse project corresponds to some actual location on my filesystem (which, in my case, it does not).  My Eclipse project is named AE3007C2, but the root is at AE3007/C2.

**Comment by 15knots** [comment] 2015-06-05 18:49
Am Donnerstag, 4. Juni 2015, 12:37:53 schrieb arette:
> Ok making it further with that option selected. Sorry for my earlier
> confusion, but I think I was somehow using an outdated cmakebuilder plugin
> at the time. But now I'm getting a problem with 'del' not found in path. 
> Suggestions?

Thanks for investigating further.

> 15:32:50 **** Clean-only build of configuration Debug for project AE3007C2
> **** del src/common/Txcallback.obj src/net/net_comm.obj AE3007C2
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^              ^^^

This looks like some of the CDT managed build slipped in again.
Strange, the cmake4eclipse plugin enforces an out-of-source build, but the 
command above indicates an in-of-source build.
For a clean build, cmake4eclipse would invoke 'make clean' (or the build 
command associated with the build script generator that was configured). This 
would result in a command like 'make clean' or 'ninja clean', but never in a 
'del src/*/obj' as above.

To be honest, I guess your project configuration is based on an inherited CDT 
configuration and You are trying to make it fit. 
Have a look at the sample project in
<https://github.com/15knots/cmake4eclipse/tree/master/testprojects/C-subsrc>.

I recommend the following settings in the project build configuration:

- C/C++ Build| Builder Settings| Builder type: External builder
- C/C++ Build| Builder Settings| Use default build command: checked
- C/C++ Build| Builder Settings| Generate Makefiles automatically: checked
- C/C++ Build| Tool Chain Editor| Current builder: CMake builder (portable)

Martin

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-09 15:43
I've followed your recommended settings above and still get the same error ass above (cannot run program "del").  My Eclipse project contains CVS info and included the MSVC toolchain plugin at the time the proect was created so Eclipse had knowledge of prepropressor symobls, etc.  So, the repeat my .project/.cproject files: 1) create new project from CVS, 2) convert the project to C/C++ selecting the MSVC toolchain, 3) switch project properties build settings to use cmake (as described above).

I may be able to get your plugin working if I remove all the other "inherited CDT configuration" features as you put it, but syntax highlighting and useful outline views are just as important in the IDE as cmake integration...i want both working.  Please let me know if providing my .project/.cproject files would help you debug your plugin.

Thanks,
Tony

**Comment by arette** [comment] 2015-06-09 16:03
I noticed above you reference 'make clean' or 'ninja clean' but note that since I'm using MSVC, my command would be 'nmake clean'.  I'm assuming your plugin supports MSVC toolchain with NMake Makefiles (I found no documentation to indicate otherwise)?  Could this just be an issue with poor support for Windows/MSVC/NMake generator?

**Comment by arette** [comment] 2015-06-09 17:36
So I just noticed that, even though the CDT Build Console indicates problem running 'del', there is also an error dialogue box that pops up and it says: "Errors running builder 'CDT Builder' on project 'AE3007C2'. can not clean programmatically: build workspace path is not specified.  Regardless, it seems that cmake4eclipse plugin DOES NOT work with Eclipse 4.4 (Luna) with MSVC toolchain and NMake Makefile generator.  Please advise on how I should proceed.

**Comment by 15knots** [comment] 2015-06-09 19:17
To shorten this:
If your project is on github, I could have a look at it.

**Comment by arette** [comment] 2015-06-09 19:20
Unfortunately it is not.  This is commercial/proprietary so I can only share bits and pieces.  I can certainly share the .project/.cproject files since they don't contain any source.

**Comment by arette** [comment] 2015-06-09 19:21
also it should be really easy to recreate using my steps above (although you will need MSVC compiler/linker and may need to install the MSVC toolchain plugin)

**Comment by 15knots** [comment] 2015-06-09 19:30
Am Dienstag, 9. Juni 2015, 08:43:34 schrieb arette:
> I've followed your recommended settings above and still get the same error
> ass above (cannot run program "del").  My Eclipse project contains CVS info
> and included the MSVC toolchain plugin at the time the proect was created

I never heard of an MSVC toolchain plugin before. Where can I find it? What 
does it do?

> so Eclipse had knowledge of prepropressor symobls, etc.  So, the repeat my
> .project/.cproject files: 1) create new project from CVS, 2) convert the
> project to C/C++ selecting the MSVC toolchain, 3) switch project properties
> build settings to use cmake (as described above).
> 
> I may be able to get your plugin working if I remove all the other
> "inherited CDT configuration" features as you put it, but syntax
> highlighting and useful outline views are just as important in the IDE as

The settings under C/C++ Build control the build, incl. buildscript 
generation.
The settings under C/C++ General control the indexer, which gives you sytax 
highlighting and others. Any settings there do not affect the cmake4eclipse 
plugin. Of course you want to adfust it to your needs.
 

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by 15knots** [comment] 2015-06-09 19:37
Am Dienstag, 9. Juni 2015, 12:22:00 schrieb arette:
> also it should be really easy to recreate using my steps above (although you
> will need MSVC compiler/linker and may need to install the MSVC toolchain
> plugin)

Unfortunately I�m on a Linux box at home.

The plugin has been tested on Windows with mingw and cywin at work.
The generator for Nmake files should work, too (its just about passing the 
appropriate option to cmake and to invoke nmake).

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-09 19:39
The MSVC toolchain is developed by Eclipse so I installed through the Help -> Install New Software menu.  You can find under Eclipse CDT provider, plug in name: MSVC Build Integration Plug-in (id: org.eclipse.cdt.msw.build).  I was originally exploring it to peform native VC build in Eclipse but have since abandoned in favor of Cmake.  However, I found cmake does a poor job "fleshing out" cmake .cproject files (e.g. defining preprocessor symbols, etc) so I found that maintaining this hook in my project is still useful.  So, I no longer use it to build, but if selected as default toolchain when creating the C++ project, than the .cproject has more goodies in it (e.g. preprocessor symbol definitions).

**Comment by arette** [comment] 2015-06-09 19:42
I'm not saying there is a problem with the NMake Makefiles generator option, but rather just invoking your plugin in general is a problem.  in other words, the error seems to indicate that Eclispe has chosen to do a 'make clean' instead of a 'cmake'.

**Comment by 15knots** [comment] 2015-06-09 19:44
Am Dienstag, 9. Juni 2015, 09:03:39 schrieb arette:
> I noticed above you reference 'make clean' or 'ninja clean' but note that
> since I'm using MSVC, my command would be 'nmake clean'.  I'm assuming your
> plugin supports MSVC toolchain with NMake Makefiles (I found no

Have a look at 
C/C++ Build | CMake | Host OS overrides | Windows | Buildscript generator

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-09 19:52
Yes I have found that option.  Now just trying to understand why Eclipse seems to be executing 'make clean' rather than 'cmake' despite the Current Builder being set to Cmake Builder (portable).  Have you tested the plugin on Eclipse Luna (4.4)?  I'm wondering if one of the APIs have changed causing your plugin to break?

**Comment by 15knots** [comment] 2015-06-09 20:24
Am Dienstag, 9. Juni 2015, 12:39:48 schrieb arette:
> The MSVC toolchain is developed by Eclipse so I installed through the Help
> -> Install New Software menu.  You can find under Eclipse CDT provider,
> plug in name: MSVC Build Integration Plug-in (id:
> org.eclipse.cdt.msw.build).  I was originally exploring it to peform native
> VC build in Eclipse but have since abandoned in favor of Cmake.  However, I
> found cmake does a poor job "fleshing out" cmake .cproject files (e.g.

Do you mean the 'Eclipse CDT4 - Unix Makefiles' generator? That one does only
generate makefile projects for CDT. The rest is up to you. I found it 
unsatisfying, too, which is the reason to write this plugin.

With cmake, you set all the preprocessor options and include dirs in the 
cmakelists.txt file.
If you have a CDT managed build project (not a Makefile project), you have to 
tell the CDT indexer about the preprocessor options in the cmakelists.txt (so 
it will be able to grey out code in its editors).
There are some choices to do that:
- add them manually (Paths and Symbols | Symbols) 
- let CDT parse the build output, grabbing each compiler invocation and detect 
the corresponding option (-D, -I). Use Preprocessot include paths.. | 
Providers to adjust that. (There is GCC build output parser, but in your case 
there should be something similar for the MS compiler.
- let CDT detect macors built-in to the compiler by enabling the GCC builtin 
specs detector (or the one for MS build in your case)

Of course, if the build script passes the option in a file instead on the 
command line, no build output parse will see them.



-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-10 13:06
Sorry, let me add more details.  Originally, I was using the cmake Eclipse CDT 4 generator to generate my Eclipse project files, however, those were not "fleshed out" enough and I could not easily find cmake equivalent commands to get what I wanted in the project files for what I already knew how to do in the Eclipse GUI.  And, since I don't want generate projects, then post-edit them in the GUI, I abondoned that cmake generator.  Now, I am just using the cmake NMake Makefile generator and I've added the project as a Makefile project with the MSVC toolchain selected as the toolchain.

**Comment by 15knots** [comment] 2015-06-10 18:37
Am Dienstag, 9. Juni 2015, 12:52:19 schrieb arette:
> Yes I have found that option.  Now just trying to understand why Eclipse
> seems to be executing 'make clean' rather than 'cmake' despite the Current

Cmake is used to generate the buildscripts (is necessary).
The 'Cmake Builder (portable)' just invokes the tool that understands the 
generated scripts. In your case, that is 'make', because you had chosen the 
makefile generator. 
In contrast, the CMake Make builder will invoke 'make' in any case, regardles 
wich generator yo selecred.

> Builder being set to Cmake Builder (portable).  Have you tested the plugin
> on Eclipse Luna (4.4)?  I'm wondering if one of the APIs have changed
> causing your plugin to break?

I use it every day at work with luna.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-10 20:05
Yeah that's what I figured but still would expect it to invoke "nmake" not "make" since I've used the NMake file generator.  I would appreciate if you would at least attempt to recreate, it should be really simple.  This will help me understand if it's a problem with the plugin/Eclipse/etc or if it's something I'm setting up incorrectly.  Thank you for your time.

1) Load eclipse ptp 4.4 on windows machine
2) install MSVC toolchain & cmake4eclipse plugin
3) create c/c++ project as an empty Makefile project, MSVC c++ toolchain (installed in step 2 above)
4) go to project properties and confirm/adjust settings as needed to match what we've spelled out earlier in this thread
5) create simple source dir structure with CmakeLists.txt files
6) Attempt to build the project

**Comment by 15knots** [comment] 2015-06-10 20:20
Am Mittwoch, 10. Juni 2015, 06:06:10 schrieb arette:
> Sorry, let me add more details.  Originally, I was using the cmake Eclipse
> CDT 4 generator to generate my Eclipse project files, however, those were
> not "fleshed out" enough and I could not easily find cmake equivalent

Citing <http://www.cmake.org/overview/>:
CMake is an extensible, open-source system that manages the build process...

Sorry, You are mixing 'build script generation' and 'Eclipse project file' 
generation here. 
Cmake focuses on *cross-platform buildscript generation*, it kindly offers 
some generators that produce project files for the IDE of your choice.
So does the cmake4eclipse plugin, plus it adds automatic-buildscript 
generation convenience to the end user.
And the CDT guys do a hard job in carving out C-compiler settings (macros, 
include path) to nicely (greyed out) display inactive code section a the C 
sources editor inside the IDE.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment] 2015-06-10 20:22
I'm not confused.  Just underwhelmed by the CDT generator included Cmake.  So underwhelmed, in fact, that I've no plans on using it.

**Comment by 15knots** [comment] 2015-08-19 20:01
fixed in  SHA: ca313f92560f941bfa2aa3b8377e6eab0b99576f

**Closed by 15knots** 2015-08-19 20:01 UTC
Labels: bug
