### ISSUE TITLE
Missing Build Targets defined within existing CMake based project

### ISSUE THREAD

**Issue by Mohawi** [15knots/cmake4eclipse#140] opened 2020-09-11 16:58 UTC
**Is your feature request related to a problem? Please describe.**
When setting up eclipse with cmake4eclipse as proposed (empty c++ project and setup according to help documents) I can configure and generate my cmake project correctly, but I am only able to build all executable targets at once. Besides executable targets, my CMake project contains custom_targets which I cannot build using the cmake4eclipse plugin. Also my project contains a lot of different executable targets, which I don't want to build all the time when I am just interested in one, since it takes a lot of time.

**Describe the solution you'd like**
I would like to have an overview of all available targets defined by my CMake project (executables and custom defined) as this is the case when generating an eclipse project from cmake and open it. 

**Describe alternatives you've considered**
CmakeTools Extension for VisualStudio code offers this feature, as well as the cmake generated eclipse project files.

**Additional context**
Tried on:
Windows 10 with MSYS2 using Unix Makefiles
Eclipse 4.16

**Comment by 15knots** [comment] 2020-09-15 18:54
You may have missed the 'Build Targets' view. Simply right click on a project there, select New... adn enter the name of the target you wish to run. Double clicking a target in that view will run it.
A different way to populate that view is to open the makefile, right click on a targetget in the outline view and select Add Build Target. This will create a target entry below the build/Debug node but that can be dragged to the project node if required.

> I would like to have an overview of all available targets defined by my CMake project (executables and custom defined) as this is the case when generating an eclipse project from cmake and open it.

Adding an overview of all targets would require to write a parser for makefiles, which is out of scope of this plugin.

**Comment by grachchr** [comment] 2022-02-15 16:09
I apologize if I'm wrong here.
 

### Brief Description
As a sample project I have chosen the c-flat project from the "cmake4eclipse-sample-projects" package.
Additional project settings:
- Enable "Build inside Docker Image" and select a Docker image.
 

### Is your feature request related to a problem? Please describe.
A)
Now I am trying to include additional build scripts via the "Build Targets". As you described above.
Example: 
```
Build Target -> Target name: my_build
Build Target -> Build command: "PATH_TO_MY_BUILD_COMMAND/my_build.sh" "arg1" "arg2"
```

Unfortunately the script ("PATH_TO_MY_BUILD_COMMAND/my_build.sh") is not called. The "CDT Build Console" output is:
```
11:31:02 **** Build of configuration Debug for project C-flat ****
[Running in image <docker.xxx.com/yyy/zzz:202009234>]
/usr/bin/make arg1 arg2 my_build
make: *** No rule to make target 'arg1'.  Stop.
"/usr/bin/make arg1 arg2 my_build" terminated with exit code 2. Build might be incomplete.
```

B)
The gcc include paths from the Docker container are not displayed in the Eclipse "Project Explorer".
For Example:
`PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include/c++/8`

Only the local ones are displayed.
`/usr/include/c++/8`

In previous versions of cmake4eclipse, the provider "CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins" took care of this. However, this provider is deprecated.

How can I display the gcc inlude paths in Eclipse "Project Explorer"?


### Describe the solution you'd like
A)
I expect the following call:
```
11:31:02 **** Build of configuration Debug for project C-flat ****
[Running in image <docker.xxx.com/yy/zzz:202009234>]
PATH_TO_MY_BUILD_COMMAND/my_build.sh arg1 arg2 my_build

```

In the versions before, A) and B) worked.
OS: Debian 10 (Buster)
Eclipse :  **Version: 2020-06 (4.16.0)**  Build id: 20200615-1200
cmake4eclipse  **2.1.4**.202103291945
CMake version: 3.13.4

 
### Useful information (current configuration)

OS: Debian 10 (Buster)
Eclipse: Version: **2021-12 (4.22.0)**  Build id: 20211202-1639
cmake4eclipse  **3.0.2**.202202072019
CMake version: 3.13.4

**Comment by 15knots** [comment] 2022-02-15 21:42
> I apologize if I'm wrong here.
> ### Brief Description
> 
> As a sample project I have chosen the c-flat project from the "cmake4eclipse-sample-projects" package. Additional project settings:
> 
>     * Enable "Build inside Docker Image" and select a Docker image.

Ah you managed to set up a container build! It would be helpful if you describe the workbench and system setup how to do that. There is an issue in the samples project: https://github.com/15knots/cmake4eclipse-sample-projects/issues/2

...
> A) Now I am trying to include additional build scripts via the "Build Targets". As you described above. Example:
> 
> ```
> Build Target -> Target name: my_build
> Build Target -> Build command: "PATH_TO_MY_BUILD_COMMAND/my_build.sh" "arg1" "arg2"
> ```

I doubt the  "Build Targets" view was intended by the makers of CDT to run arbitrary scripts. At least I did not see this intention in cmake4eclipse 3.
Please file a separate issue for this.

> 
> B) The gcc include paths from the Docker container are not displayed in the Eclipse "Project Explorer". For Example: `PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include/c++/8`
> 
> Only the local ones are displayed. `/usr/include/c++/8`
> 
> In previous versions of cmake4eclipse, the provider "CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins" took care of this. However, this provider is deprecated.

Sorry, I do not know how to set up the workbench and system to run builds in a docker container.
Please file a separate issue with instruction how to set it up.

**Comment by grachchr** [comment] 2022-05-04 16:13
## A)
Duplicate of #168 

`The script under "Build Targets" is not invoked #168`  BUG-CLOSED
[https://github.com/15knots/cmake4eclipse/issues/168](url)

**=> Thanks for the fix**.


## B)
### Describe the bug

No include paths are displayd in the Eclipse "Project Explorer" (Neither the project include paths nor the system include paths.)
- project include paths:
/mnt/MyMount/MyCommonSrcs/MyIncludes

- system include paths:
PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_**docker**_sock/docker_xxx_com_yy_zzz_202009234/**usr/include/c++/8**


![Eclipse_ProjectExplorer_NoIncludePaths](https://user-images.githubusercontent.com/80275938/166712880-18611596-4987-4777-91b0-0e4850b81cfa.JPG)



### Setup
My set up is described here:
[https://github.com/15knots/cmake4eclipse/issues/168](url)


### Describe the problem
In previous versions of cmake4eclipse, the provider **CMAKE_EXPORT_COMPILE_COMMANDS (Compiler Built-ins)** took care of this. This provider is deprecated. So I use **CMake Compilation DB**. However, this new provider does not seem to work.

![Eclipse_ProviderCmakeCompilationDb](https://user-images.githubusercontent.com/80275938/166716724-3561e051-0cd7-479a-a799-5eea622ad525.JPG)


### Expected behavior
![Eclipse_ProjectExplorer_WithIncludePaths](https://user-images.githubusercontent.com/80275938/166722066-9b1d8b4c-83b1-45ea-ba9f-8d260aad97b3.JPG)


//--------------------------------------
// **This is the configuration that works** 
//--------------------------------------
![Eclipse_ProviderCmakeExportCompileCommands](https://user-images.githubusercontent.com/80275938/166722132-0d73846e-364b-4b18-bb2d-9c82c279da5f.JPG)

OS: Debian 10 (Buster)
Eclipse: Version: **2020-06 (4.16.0)** Build id: 20200615-1200
cmake4eclipse **2.1.4**
CMake version: 3.13.4


## Useful information (current configuration)

OS: Debian 11 (Bullseye)
Eclipse: Version: **2022-03 (4.23.0**) Build id:20220310-1457
cmake4eclipse **3.0.3**.202203311948
CMake version: 3.13.4

**Comment by 15knots** [comment] 2022-05-04 18:03
Try to upgrade to CDT 10.6.1, it has some bugs fixed that might affect this (https://wiki.eclipse.org/CDT/User/NewIn106)

**Comment by grachchr** [comment] 2022-05-05 11:31
Also an update did not bring any change.

![Eclipse_CdtVersion](https://user-images.githubusercontent.com/80275938/166914088-cce3c72e-9881-4706-8e23-90a4d3c4ea37.JPG)

It is still not possible for me to display an include list in the Eclipse Project Explorer. I have also tried different Java engines (v11 and v17).

If I include the provider **CDT Cross GCC Built-in Compiler Settings** ("Use global provider shared between projects" is enabled), I get some system paths displayed. However, these are wrong. Instead of showing me the paths that are in the docker image, the host paths are shown. 

- Paths on docker (these paths should be displayed): 
PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include
PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include/c++/**8**

- Paths displayed by the Eclipse Project Explorer (on host I have **c++/10**): 
PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include
PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234/usr/include/c++/**10** => This is grayed out.

I don't know what I'm doing wrong. The Eclipse Workspace Folder contains the correct system include paths from the docker container  (-> PATH_TO_ECLIPSE_WORKING_SPACE/MyWs/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/docker_xxx_com_yy_zzz_202009234).

How to choose the Providers if you have a CMake project (Current toolchain: **CMake driven** // Current builder: **CMake Builder**) that is compiled in a docker container?

**Closed** 2023-02-13 21:18 UTC
Labels: feedback awaited
