### ISSUE TITLE
CMakeFiles, cache and others generated into wrong directory

### ISSUE THREAD

**Issue by Krakonos** [15knots/cmake4eclipse#26] opened 2017-04-06 17:47 UTC
Hi!

We're running into some kind of strange trouble with the cmake4eclipse plugin (latest version from eclipse marketplace). We are developing a project with CMake and arm embedded toolchain, and thus using the cross-compiler. With some minor issues, and arm-none-eabi-* in PATH, it seems to work fine. However, if the compiler is not found, the cmake fails with the relevant errors (see below). 

The strange thing about this is, that the (incomplete) cache is not generated in the project's directory as usual, but in the working directory of Eclipse (in this case /tmp, however we observed the same when running eclipse "from" home). The build directories are not even generated. 

In case we're running eclipse with PWD=HOME, this complicates the matter further -- when the problem is fixed, the broken cache from home is loaded into cmake, and causes mysterious cmake failures.

Any ideas on what could be wrong, or how to get more information about how cmake (in which directory) is executed and why? 

Thanks!

```
cmake -DCMAKE_BUILD_TYPE:STRING=Debug --debug-output -DCMAKE_BUILD_TYPE:INTERNAL=Xplain -G "Unix Makefiles" /home/krakonos/XXX
Running with debug output on.
-- The C compiler identification is unknown
   Called from: [3]	/usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake
                [2]	/usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake
                [1]	/home/krakonos/XXX/CMakeLists.txt
-- The CXX compiler identification is unknown
   Called from: [3]	/usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake
                [2]	/usr/share/cmake-3.7/Modules/CMakeDetermineCXXCompiler.cmake
                [1]	/home/krakonos/XXX/CMakeLists.txt
CMake Error at CMakeLists.txt:28 (project):
  The CMAKE_C_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


   Called from: [1]	/home/krakonos/XXX/CMakeLists.txt
CMake Error at CMakeLists.txt:28 (project):
  The CMAKE_CXX_COMPILER:

    arm-none-eabi-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


   Called from: [1]	/home/krakonos/XXX/CMakeLists.txt
-- Configuring incomplete, errors occurred!
See also "/tmp/CMakeFiles/CMakeOutput.log".
See also "/tmp/CMakeFiles/CMakeError.log".
```

**Comment by 15knots** [comment] 2017-04-06 19:58
I'm not quite sure whether this issue is related to the plugin itself.
What does it work, if you invoke
`cmake -DCMAKE_BUILD_TYPE:STRING=Debug --debug-output -DCMAKE_BUILD_TYPE:INTERNAL=Xplain -G "Unix Makefiles" /home/krakonos/XXX
`
from the command line?

I looks you set `CMAKE_CXX_COMPILER` in your CMakeLists.txt.
AFAIK, the proper way to specify a tool-chain for cmake is to use a [toolchain](http://www.vtk.org/Wiki/CMake_Cross_Compiling#The_toolchain_file) file.
Please note that the toolchain in the Eclipse project settings has no impact on the buildscript generation of cmake, it is used by CDT to generate makefiles.

**Comment by 15knots** [comment] 2017-04-06 20:13
> Any ideas on what could be wrong, or how to get more information about how cmake (in which directory) is executed and why?

The plugin will create a build directory `<your project dir>/build/<configuration name>` if necessary. In your case, this will be `/home/krakonos/XXX/Xplain`.
If a build is started and no CMakeCache.txt file exists in that directory, `cmake` will be invoked with its CWD set to that directory (out of source build). Additionally, some of the rules in the generated makefiles will ensure that cmake is invoked if one of the CMakeLists changes.

**Comment by Krakonos** [comment] 2017-04-07 06:26
> I'm not quite sure whether this issue is related to the plugin itself.
> [...]

Invoking that command works as expected. It creates the cmake stuff in the currect directory, regardless of success or failure (ie if it could not find the compiler).

> I looks you set CMAKE_CXX_COMPILER in your CMakeLists.txt.

No, we have a toolchain file, with this contents:
```
set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_SYSTEM_PROCESSOR cortex-m0)

set (CMAKE_C_COMPILER   arm-none-eabi-gcc)
set (CMAKE_CXX_COMPILER arm-none-eabi-g++)

set (CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
```
And it works fine outside eclipse. We didn't try to set this stuff in Eclipse, but it's good to know that it's not used.

For some reason it seems the directory is not created (or gets deleted before the build finishes), and cmake is executed in the working directory of eclipse. I have modified our CMakeLists to execute pwd as soon as possible:

```
execute_process(
  COMMAND "pwd"
)
```

Now running cmake from the eclipse plugin, I get:

```
8:21:17 AM **** Buildscript generation of configuration cmake-xplain for project rtos_jot
cmake -DCMAKE_BUILD_TYPE:STRING=Debug --debug-output -DCMAKE_BUILD_TYPE:INTERNAL=Xplain -G "Unix Makefiles" /home/krakonos/XXX 
Running with debug output on.
/tmp
-- The C compiler identification is unknown
[...]
```
So it seems that cmake does the right thing, but is executed in the wrong context. But again, I'm unsure as to why. I even tried creating the directory XXX/Xplain by hand, and it didn't change anything.

**Comment by Krakonos** [comment] 2017-04-07 06:41
Allright, as I've been tinkering with #27, I've found something new, possibly hinting at the problem:
The directories are subdirectories of build, so XXX/build/Xplain (or whatever the target is called). They get created _only_ the first time the build type is selected in the build ("hammer") menu. When it gets deleted (for example, by git clean -xfd, hg purge -all or similar), it never gets re-created. Even if different build type is selected inbetween.

I think the correct behaviour would be to create the directory whenever it does not exist, or fail with some reasonable message when it does not (or even both), preventing the creation of cmakecache in $HOME.

Can you confirm this behaviour?

**Comment by 15knots** [comment] 2017-04-09 18:44
The directory is created, if you actually **build** your project; selecting a different build type does not trigger creation.
Both cmake and make are invoked with that directory as the CWD. Trying to start a process with a non-existing working directory will be rejected by the OS-kernel (at least on linux or windows). So how can cmake create files in $HOME if it does not get started?

**Comment by Krakonos** [comment] 2017-04-10 05:53
Strange, that does not match what I observed. I will investigate further once I get back from vacation and let you know!

**Comment by nolange** [comment] 2017-05-08 20:37
I observe the same thing. If you build via eclipse (and refresh the project tree if it doesnt automatically), then delete the build directory **outside of eclipse**, then eclipse will still display the directory.
The next CMake build then will display an Error "Launch attempt in non existent working directory" and build in a different directory - I guess the CWD which usually is $HOME. Like the "cd" to the work directory failed, but the build was still started.

It guess that #32 was caused by the same issue? (deleting files from $HOME if you are unlucky)

**Comment by 15knots** [comment] 2017-05-12 19:32
> I observe the same thing. If you build via eclipse (and refresh the project tree if it doesnt automatically), then delete the build directory outside of eclipse, then eclipse will still display the directory.

Yes, eclipse will still display the directory until it decides to do an automatic refresh. That's part of eclipses resource concept.

Anyway, I can reproduce the "Launch attempt in non existent working directory"-error. I get two of them:
1. One with a stack trace that indicates that the **internal** builder runs a clean build (`at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.cleanWithInternalBuilder(CommonBuilder.java:1209)`). This is really crazy, since the project is configured to use the **external** builder.
1. The second error happens when the plugin tries to re-generate the build scripts (`	at de.marw.cdt.cmake.core.internal.BuildscriptGenerator.regenerateMakefiles(BuildscriptGenerator.java:253)`). This method does not check whether the build dir exists (but BuildscriptGenerator.generateMakefiles() does) --> BUG.

Additionally I can confirm, that the files are generated in the CWD, if the build directory does not exist. This must be caused by some magic in CDT`s Spawner class: It apparently complains about none-existing directory and despite of that it them runs the command in the current working directory. An existence-check in regenerateMakefiles() should fix that.

**Closed** 2017-05-17 21:10 UTC
Labels: bug
